#ifndef EBPF_HELPERS_H_
#define EBPF_HELPERS_H_

enum ebpf_helper_id
{
  EBPF_HELPER_QUEUE_TAIL = 1001,
  EBPF_HELPER_QUEUE_ENQUEUE = 1002,
  EBPF_HELPER_MEMCPY = 1003,
  EBPF_HELPER_PRINT = 1004,
  EBPF_HELPER_IPV4_CKSUM = 1005,
  EBPF_HELPER_IPV4_UDPTCP_CKSUM = 1006,
  EBPF_HELPER_SCHED_HEAD = 1007,
  EBPF_HELPER_SCHED_POP = 1008,
  EBPF_HELPER_SCHED_ADD = 1009,
  EBPF_HELPER_MAP_GET = 1010,
  EBPF_HELPER_MAP_LOOKUP = 1011,
  EBPF_HELPER_QUEUE_HEAD = 1012,
  EBPF_HELPER_QUEUE_DEQUEUE = 1013,
  EBPF_HELPER_RDTSC = 1014,
  EBPF_HELPER_RATE_DELAY_TSC = 1015,
  EBPF_HELPER_SPIN_LOCK = 1016,
  EBPF_HELPER_SPIN_UNLOCK = 1017,
  EBPF_HELPER_SCHED_REMOVE = 1018,
  EBPF_HELPER_NOW_US = 1019,
};

#define EBPF_EXT_HELPER_QUEUE_TAIL "_bpf_helper_ext_1001"
#define EBPF_EXT_HELPER_QUEUE_ENQUEUE "_bpf_helper_ext_1002"
#define EBPF_EXT_HELPER_MEMCPY "_bpf_helper_ext_1003"
#define EBPF_EXT_HELPER_SCHED_HEAD "_bpf_helper_ext_1007"
#define EBPF_EXT_HELPER_SCHED_POP "_bpf_helper_ext_1008"
#define EBPF_EXT_HELPER_SCHED_ADD "_bpf_helper_ext_1009"
#define EBPF_EXT_HELPER_MAP_GET "_bpf_helper_ext_1010"
#define EBPF_EXT_HELPER_MAP_LOOKUP "_bpf_helper_ext_1011"
#define EBPF_EXT_HELPER_QUEUE_HEAD "_bpf_helper_ext_1012"
#define EBPF_EXT_HELPER_QUEUE_DEQUEUE "_bpf_helper_ext_1013"
#define EBPF_EXT_HELPER_RDTSC "_bpf_helper_ext_1014"
#define EBPF_EXT_HELPER_RATE_DELAY_TSC "_bpf_helper_ext_1015"
#define EBPF_EXT_HELPER_SCHED_REMOVE "_bpf_helper_ext_1018"
#define EBPF_EXT_HELPER_NOW_US "_bpf_helper_ext_1019"

#endif
